### ISSUE TITLE
[hacktoberfest] [easy] Write a README

### ISSUE THREAD

**Issue by nk521** [nk521/2020_linux_calendar#6]
Just edit the README.md so that it looks something like this:
-> (horizontal line)
-> fedora artwork
-> (pic of fedora artwork calendar)
-> (horizontal line)
.
.
.

**Comment by shivang-saxena** [comment]
Can i take, what is the mean of fedora artwork

**Comment by nk521** [comment]
Thank you @Zeustopher for making a PR :)
Happy Hacktoberfest!
